import { NextResponse } from "next/server"
import type { UserProfile, FitnessPlan } from "@/lib/types"
import { fixAndParseJSON } from "@/lib/json-fixer"
import { buildFitnessPlanPrompt, generateWithGroq, generateWithPollinations } from "@/lib/ai-client"
import { generateFallbackPlan } from "@/lib/plan-generator"
import { prisma } from "@/lib/prisma"
import { auth } from "@/auth"

export async function POST(request: Request) {
  try {
    const session = await auth()
    const body = await request.json()
    const profile: UserProfile = body.profile || body
    const isRegenerate: boolean = body.isRegenerate || false
    const saveToDb: boolean = body.saveToDb !== undefined ? body.saveToDb : true

    let pastWorkouts = "";
    if (session?.user?.id) {
      const recentSessions = await prisma.workoutSession.findMany({
        where: { userId: session.user.id, status: "COMPLETED" },
        orderBy: { createdAt: "desc" },
        take: 3,
        include: { feedback: true }
      });
      if (recentSessions.length > 0) {
        pastWorkouts = recentSessions.map(s => {
          let fb = s.feedback ? ` Difficulty: ${s.feedback.difficulty}, Energy: ${s.feedback.energyLevel}/5, Soreness: ${s.feedback.sorenessLevel}/5.` : "";
          if (s.feedback?.notes) fb += ` Notes: ${s.feedback.notes}.`;
          return `Workout '${s.workoutName}': Completed ${s.completionPercentage}% in ${s.duration}m.${fb}`;
        }).join("\n");
      }
    }

    const exerciseCount = isRegenerate ? 6 : 4
    const prompt = buildFitnessPlanPrompt(profile, exerciseCount, pastWorkouts)

    let plan: FitnessPlan

    try {
      // 1st choice: Groq
      const text = await generateWithGroq(prompt)
      plan = fixAndParseJSON(text)
      console.log("✅ Plan generated by: GROQ")
    } catch (groqError) {
      console.log("⚠️ Groq failed, falling back to Pollinations:", (groqError as Error).message)
      try {
        // 2nd choice: Pollinations
        const text = await generateWithPollinations(prompt)
        plan = fixAndParseJSON(text)
        console.log("✅ Plan generated by: POLLINATIONS (fallback)")
      } catch (pollinationsError) {
        // Last resort: hardcoded profile-based plan
        console.log("⚠️ Both AI providers failed, generating profile-based plan")
        plan = generateFallbackPlan(profile, isRegenerate)
        console.log("✅ Plan generated by: HARDCODED FALLBACK")
      }
    }

    // CRITICAL FIX: Ensure dietPlan, motivation, and tips are never missing (in case AI hallucinates or truncates)
    const fallback = generateFallbackPlan(profile, isRegenerate);
    
    // Ensure plan is a valid object
    if (!plan || typeof plan !== 'object' || Array.isArray(plan)) {
      plan = fallback;
    } else {
      if (!plan.dietPlan || typeof plan.dietPlan !== 'object' || Object.keys(plan.dietPlan).length === 0) plan.dietPlan = fallback.dietPlan;
      if (!plan.motivation || typeof plan.motivation !== 'string') plan.motivation = fallback.motivation;
      if (!plan.tips || !Array.isArray(plan.tips) || plan.tips.length === 0) plan.tips = fallback.tips;
      if (!plan.workoutPlan || !Array.isArray(plan.workoutPlan) || plan.workoutPlan.length === 0) plan.workoutPlan = fallback.workoutPlan;
      if (!plan.warmup || !Array.isArray(plan.warmup)) plan.warmup = [];
      if (!plan.cooldown || !Array.isArray(plan.cooldown)) plan.cooldown = [];
    }

    let savedPlanId = null;
    if (session?.user?.id && saveToDb) {
      try {
        const savedPlan = await prisma.fitnessPlan.create({
          data: {
            userId: session.user.id,
            profile: profile as any,
            plan: plan as any,
          },
        })
        savedPlanId = savedPlan.id;
        console.log(`✅ Saved plan to DB for user ${session.user.id}`)
      } catch (dbError) {
        console.error("❌ Failed to save plan to database:", dbError)
      }
    } else if (!saveToDb) {
      console.log(`ℹ️ Skipped saving plan to DB (saveToDb is false)`)
    }

    return NextResponse.json({ id: savedPlanId, ...plan })
  } catch (error) {
    console.error("Error generating plan:", error)
    return NextResponse.json({ error: "Failed to generate plan. Please try again." }, { status: 500 })
  }
}
