import { NextResponse } from "next/server"
import type { UserProfile, FitnessPlan } from "@/lib/types"
import { fixAndParseJSON } from "@/lib/json-fixer"
import { buildFitnessPlanPrompt, generateWithGroq, generateWithPollinations } from "@/lib/ai-client"
import { generateFallbackPlan } from "@/lib/plan-generator"
import { prisma } from "@/lib/prisma"
import { auth } from "@/auth"

export async function POST(request: Request) {
  try {
    const session = await auth()
    const body = await request.json()
    const profile: UserProfile = body.profile || body
    const isRegenerate: boolean = body.isRegenerate || false

    const exerciseCount = isRegenerate ? 6 : 4
    const prompt = buildFitnessPlanPrompt(profile, exerciseCount)

    let plan: FitnessPlan

    try {
      // 1st choice: Groq
      const text = await generateWithGroq(prompt)
      plan = fixAndParseJSON(text)
      console.log("✅ Plan generated by: GROQ")
    } catch (groqError) {
      console.log("⚠️ Groq failed, falling back to Pollinations:", (groqError as Error).message)
      try {
        // 2nd choice: Pollinations
        const text = await generateWithPollinations(prompt)
        plan = fixAndParseJSON(text)
        console.log("✅ Plan generated by: POLLINATIONS (fallback)")
      } catch (pollinationsError) {
        // Last resort: hardcoded profile-based plan
        console.log("⚠️ Both AI providers failed, generating profile-based plan")
        plan = generateFallbackPlan(profile, isRegenerate)
        console.log("✅ Plan generated by: HARDCODED FALLBACK")
      }
    }

    if (session?.user?.id) {
      try {
        await prisma.fitnessPlan.create({
          data: {
            userId: session.user.id,
            profile: profile as any,
            plan: plan as any,
          },
        })
        console.log(`✅ Saved plan to DB for user ${session.user.id}`)
      } catch (dbError) {
        console.error("❌ Failed to save plan to database:", dbError)
      }
    }

    return NextResponse.json(plan)
  } catch (error) {
    console.error("Error generating plan:", error)
    return NextResponse.json({ error: "Failed to generate plan. Please try again." }, { status: 500 })
  }
}
